=== g0v/ambassador/bin/schema/v1.json
{
  "id": "https://raw.githubusercontent.com/g0v/ambassador/master/bin/schema/v1.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "author"
  ],
  "properties": {
    "author": {
      "title": "專案作者",
      "description": "Project author",
      "type": "string",
      "minLength": 1
    },
    "status": {
      "title": "專案狀態",
      "description": "Project status",
      "type": "string",
      "enum": [
        "Planning",
        "planning",
        "Pre-alpha",
        "pre-alpha",
        "Alpha",
        "alpha",
        "Beta",
        "beta",
        "Production",
        "production",
        "Released",
        "released",
        "Archived",
        "archived",
        "Stable",
        "stable",
        "Mature",
        "mature",
        "Inactive",
        "inactive",
        "Magic",
        "magic"
      ]
    },
    "name": {
      "title": "專案名稱（英文）",
      "description": "Project name",
      "type": "string",
      "minLength": 1
    },
    "name_zh": {
      "title": "專案名稱（中文）",
      "description": "Chinese project name",
      "type": "string",
      "minLength": 1
    },
    "description": {
      "title": "專案描述（英文）",
      "description": "Project description",
      "type": "string"
    },
    "description_zh": {
      "title": "專案描述（中文）",
      "description": "Chinese project description",
      "type": "string"
    },
    "homepage": {
      "title": "網頁",
      "description": "Homepage url",
      "type": "string",
      "format": "uri"
    },
    "thumbnail": {
      "title": "縮圖",
      "description": "Thumbnail",
      "oneOf": [
        { "type": "string", "format": "uri" },
        { "type": "array", "items": { "type": "string", "format": "uri" } }
      ]
    },
    "document": {
      "title": "文件",
      "description": "Document",
      "type": "string",
      "format": "uri"
    },
    "repository": {
      "title": "Repo 工作資料區",
      "description": "Repository url",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["git", "hg", "svn", "cvs", "svk"]
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": ["type", "url"]
    },
    "licenses": {
      "title": "專案授權",
      "description": "Licenses",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": { "type": "string" }
        },
        "required": ["type"]
      }
    },
    "keywords": {
      "title": "專案關鍵字",
      "description": "Keywords",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "audience": {
      "title": "目標受眾",
      "description": "Target audience",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["contributor", "public", "developer"]
      }
    },
    "products": {
      "title": "產出",
      "description": "Productions",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "partOf": {
      "title": "Part Of",
      "description": "Parent project",
      "type": "string"
    },
    "projects": {
      "title": "Projects",
      "description": "Parent projects",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "contributors": {
      "title": "貢獻者",
      "description": "Contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "needs": {
      "title": "徵求支援",
      "description": "Needs",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["designer", "writer", "programmer", "money", "txt"]
      }
    }
  }
}

=== g0v/ambassador/data/v1/g0v/councilor-voter-guide/g0v.json
{
  "author": "thewayiam",
  "status": "alpha",
  "name": "councilor-voter-guide",
  "description": "Taiwan Councilorss Voting Guide",
  "description_zh": "議員投票指南",
  "homepage": "http://councils.g0v.tw/",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/councilor-voter-guide"
  },
  "licenses": [
    {
      "type": "CC0 1.0 Universal"
    }
  ],
  "keywords": [
    "councilor",
    "議員",
    "投票指南"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website",
    "api"
  ],
  "projects": [],
  "contributors": [
    "thewayiam",
    "c3h3",
    "x4base",
    "ipaaa",
    "theacat",
    "Swind",
    "chhsiao1981",
    "daikeren",
    "y12studio",
    "s890081tonyhsu",
    "seadog007",
    "walkingice",
    "pcchou",
    "rz12345",
    "Kinvil",
    "asika",
    "AlcHawk",
    "slashtu"
  ],
  "needs": [
    "writer",
    "programmer",
    "designer"
  ]
}

=== g0v/ambassador/data/v1/g0v/api.ly/g0v.json
{
  "author": "clkao",
  "contributors": [
    "walkingice"
  ],
  "status": "alpha",
  "homepage": "http://api.ly.g0v.tw",
  "name": "api.ly",
  "name_zh": "g0v 立法院資料 API",
  "description": " Source code of api.ly.g0v.tw to provide RESTFUL api",
  "description_zh": "api.ly.g0v.tw 的原始碼，提供 RESTFUL 的 api",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/api.ly"
  },
  "licenses": [
    {
      "type": "MIT"
    }
  ],
  "keywords": [
    "livescript",
    "postgresql",
    "pgrest"
  ],
  "audience": [
    "contributor"
  ],
  "products": [
    "api",
    "data"
  ],
  "projects": [
    "ly"
  ],
  "needs": [
    "programmer"
  ]
}

=== g0v/ambassador/data/v1/g0v/amis-moedict/g0v.json
{
  "author": "au",
  "status": "beta",
  "name": "moedict",
  "description": "'Amis moedict: Dictionaries from Safolu Kacaw Lalanges, Virginia Fey, Louis Pourrias, Maurice Poinsot",
  "description_zh": "阿美語萌典，目前有蔡中涵、方敏英、博利亞、潘世光字典",
  "homepage": "https://moedict.tw/",
  "document": "http://3du.tw/",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/amis-moedict"
  },
  "licenses": [
    {
      "type": "CC0"
    }
  ],
  "keywords": [
    "nodejs",
    "react",
    "scss",
    "bootstrap3"
  ],
  "audience": [
    "contributor"
  ],
  "products": [
    "website", "app"
  ],
  "projects": [
    "3du"
  ],
  "contributors": [
    "wildjcrt",
    "miaoski",
    "audreyt",
    "leo424y",
    "moon_c",
    "misscs",
    "a-tsioh",
    "PeterDaveHello",
    "yhsiang",
    "caasi",
    "viirya",
    "gugod",
    "ethantw"
  ],
  "thumbnail": [
    "https://amis.moedict.tw/2017-Amis-Logo.png"
  ],
  "needs": [
    "programmer",
    "designer",
    "txt"
  ]
}

=== g0v/ambassador/data/v1/g0v/inLiveTwTextChrome/g0v.json
{
  "author": "miaoski",
  "contributors": [
    "白凜希"
  ],
  "status": "alpha",
  "name": "inLiveTwTextChrome",
  "name_zh": "Chromecast用的inLiveTW",
  "description": "Play inLiveTW on Chromecast from Chrome browser extension.",
  "description_zh": "透過 Chrome 瀏覽器的 Google Cast 擴充套件，在 ChromeCast 上播放 InLiveTw 的事件、報導、直播。",
  "homepage": "http://miaoski.idv.tw/inLiveTw-ChromeCast/",
  "repository": {
    "type": "git",
    "url": "https://github.com/miaoski/inLiveTwTextChrome"
  },
  "licenses": [
    {
      "type": "Apache2"
    }
  ],
  "keywords": [
    "inlivetw"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "inLiveTw"
  ],
  "thumbnail": "https://avatars0.githubusercontent.com/u/7513555?s=200",
  "needs": [
    "designer",
    "programmer"
  ]
}

=== g0v/ambassador/data/v1/g0v/abroadplay/g0v.json
{
  "author": "Bert Wang",
  "contributors": [
    "Bert Wang"
  ],
  "status": "alpha",
  "homepage": "http://hack.g0v.tw/abroadplay/nOWhTpJPKx7",
  "name": "abroadplay",
  "name_zh": "公務員出國考察追蹤網",
  "description": "tracking abroad - stroke, the number",
  "description_zh": "追蹤公務員出國考察的-行程、人數",
  "document": "我們公務人員出國考察其實是很像挖馬路，除了很浮濫，而且常常是一再重覆。常常金管會、經濟部、經建會大家都去考察，或是每年4Q為了消化預算，就是考察旺季，讓外館人員應接不暇。這對一個財政吃緊的國家是沒有必要的浪費。更不要講一堆被考察的城市都是些知名觀光景點。",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/abroadplay"
  },
  "licenses": [
    {
      "type": ""
    }
  ],
  "keywords": [
    "abroad"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "abroadplay"
  ],
  "thumbnail": "",
  "needs": [
    "designer",
    "programmer",
    "writer"
  ]
}
