=== g0v/ambassador/bin/schema/v1.json
{
  "id": "https://raw.githubusercontent.com/g0v/ambassador/master/bin/schema/v1.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "author"
  ],
  "properties": {
    "author": {
      "title": "專案作者",
      "description": "Project author",
      "type": "string",
      "minLength": 1
    },
    "status": {
      "title": "專案狀態",
      "description": "Project status",
      "type": "string",
      "enum": [
        "Planning",
        "planning",
        "Pre-alpha",
        "pre-alpha",
        "Alpha",
        "alpha",
        "Beta",
        "beta",
        "Production",
        "production",
        "Released",
        "released",
        "Archived",
        "archived",
        "Stable",
        "stable",
        "Mature",
        "mature",
        "Inactive",
        "inactive",
        "Magic",
        "magic"
      ]
    },
    "name": {
      "title": "專案名稱（英文）",
      "description": "Project name",
      "type": "string",
      "minLength": 1
    },
    "name_zh": {
      "title": "專案名稱（中文）",
      "description": "Chinese project name",
      "type": "string",
      "minLength": 1
    },
    "description": {
      "title": "專案描述（英文）",
      "description": "Project description",
      "type": "string"
    },
    "description_zh": {
      "title": "專案描述（中文）",
      "description": "Chinese project description",
      "type": "string"
    },
    "homepage": {
      "title": "網頁",
      "description": "Homepage url",
      "type": "string",
      "format": "uri"
    },
    "thumbnail": {
      "title": "縮圖",
      "description": "Thumbnail",
      "oneOf": [
        { "type": "string", "format": "uri" },
        { "type": "array", "items": { "type": "string", "format": "uri" } }
      ]
    },
    "document": {
      "title": "文件",
      "description": "Document",
      "type": "string",
      "format": "uri"
    },
    "repository": {
      "title": "Repo 工作資料區",
      "description": "Repository url",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["git", "hg", "svn", "cvs", "svk"]
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": ["type", "url"]
    },
    "licenses": {
      "title": "專案授權",
      "description": "Licenses",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": { "type": "string" }
        },
        "required": ["type"]
      }
    },
    "keywords": {
      "title": "專案關鍵字",
      "description": "Keywords",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "audience": {
      "title": "目標受眾",
      "description": "Target audience",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["contributor", "public", "developer"]
      }
    },
    "products": {
      "title": "產出",
      "description": "Productions",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "partOf": {
      "title": "Part Of",
      "description": "Parent project",
      "type": "string"
    },
    "projects": {
      "title": "Projects",
      "description": "Parent projects",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "contributors": {
      "title": "貢獻者",
      "description": "Contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "needs": {
      "title": "徵求支援",
      "description": "Needs",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["designer", "writer", "programmer", "money", "txt"]
      }
    }
  }
}

=== g0v/ambassador/data/v1/g0v/laweasyread-front/g0v.json
{
  "author": "kong0107",
  "status": "beta",
  "thumbnail": "https://raw.github.com/g0v/laweasyread-front/master/icon.png",
  "name": "LawEasyRead client",
  "name_zh": "法規亦毒氣",
  "description": "Parse the contents of webpage to view Taiwan's law articles/websites easier.",
  "description_zh": "將網頁中的法規、條文、大法官解釋、判決字號均加上連結。",
  "homepage": "http://g0v.github.io/laweasyread-front",
  "document": "http://hack.g0v.tw/laweasyread",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/laweasyread-front"
  },
  "licenses": [
    {
      "type": "modified MIT",
      "url": "https://github.com/g0v/laweasyread-front#license"
    }
  ],
  "keywords": [
    "JavaScript",
    "law"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "browserext",
    "script"
  ],
  "projects": [
    "laweasyread"
  ],
  "contributors": [
    "kong0107",
    "czchen",
    "kcliu"
  ],
  "needs": [
    "designer",
    "programmer",
    "writer"
  ]
}

=== g0v/ambassador/data/v1/g0v/laweasyread/g0v.json
{
  "author": "czchen",
  "status": "alpha",
  "thumbnail": "https://raw.github.com/g0v/laweasyread-front/master/icon.png",
  "name": "lawEasyRead",
  "description": "API for Taiwan Law",
  "description_zh": "台灣法規的API",
  "homepage": "http://laweasyread.herokuapp.com/",
  "document": "http://hack.g0v.tw/laweasyread",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/laweasyread"
  },
  "licenses": [
    {
      "type": "MIT"
    }
  ],
  "keywords": [
    "law",
    "LiveScript"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "api",
    "website"
  ],
  "projects": [
    "laweasyread"
  ],
  "contributors": [
    "czchen",
    "kcliu",
    "kong0107"
  ],
  "needs": [
    "designer",
    "programmer",
    "writer"
  ]
}

=== g0v/ambassador/data/v1/g0v/i64885/g0v.json
{
  "author": "mindos",
  "contributors": [
    "isabel.hou",
    "zoe",
    "cpyang"
  ],
  "status": "alpha",
  "name": "i64885",
  "name_zh": "i64885公益律師呼叫平台",
  "description": "A request tracking and notification system for legal aid.  Helping political victims in emergency situation.",
  "description_zh": "公益律師呼叫平台",
  "homepage": "http://i64885.tw/",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/i64885"
  },
  "licenses": [
    {
      "type": "MIT"
    }
  ],
  "keywords": [
    "pgrest"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "i64885"
  ],
  "thumbnail": "https://raw.github.com/g0v/i64885/master/thumbnail.png",
  "needs": [
    "designer",
    "programmer",
    "writer"
  ]
}

=== g0v/ambassador/data/v1/g0v/TWDoorplates/g0v.json
{
  "author": "ShivaHuang",
  "status": "alpha",
  "name": "TWDoorplates",
  "name_zh": "內政部戶政司地址查詢工具",
  "description": "The interface of doorplate searching system from Department of Household Registration, M.O.I. sucks, so we build our own.",
  "description_zh": "鑑於內政部戶政司官方的地址查詢網站使用介面不人性，因此建構一個易於使用的查詢工具。方便連署書整理志工查詢補完連署人地址。",
  "homepage": "http://ris.g0v.tw",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/TWDoorplates"
  },
  "licenses": [
    {
      "type": "MIT"
    }
  ],
  "keywords": [
    "Ruby on Rails",
    "連署",
    "地址"
  ],
  "audience": [
    "contributor",
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "Tools"
  ],
  "contributors": [
    "ShivaHuang"
  ],
  "needs": [
    "designer"
  ]
}

=== g0v/ambassador/data/v1/g0v/moedict-data/g0v.json
{
  "author": "kcwu",
  "status": "stable",
  "name": "moedict-data",
  "description": "Parsed dictionary data from Ministry of Education",
  "description_zh": "教育部重編國語辭典 資料檔",
  "homepage": "http://3du.tw/",
  "document": "https://github.com/g0v/moedict-process/wiki",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/moedict-data"
  },
  "licenses": [
    {
      "type": "MIT"
    }
  ],
  "keywords": [
    "dictionary",
    "json"
  ],
  "audience": [
    "developer"
  ],
  "products": [
    "data"
  ],
  "projects": [
    "3du"
  ],
  "contributors": [
    "au",
    "kcwu",
    "poga"
  ],
  "needs": []
}

=== g0v/ambassador/data/v1/g0v/moedict-webkit/g0v.json
{
  "author": "au",
  "status": "beta",
  "name": "moedict",
  "description": "moedict: Dictionaries from Ministry of Education",
  "description_zh": "萌典: 教育部字典匯總",
  "homepage": "https://moedict.tw/",
  "document": "http://3du.tw/",
  "repository": {
    "type": "git",
    "url": "https://github.com/audreyt/moedict-webkit"
  },
  "licenses": [
    {
      "type": "CC0"
    }
  ],
  "keywords": [
    "livescript",
    "sass",
    "bootstrap"
  ],
  "audience": [
    "contributor"
  ],
  "products": [
    "website",
    "app"
  ],
  "projects": [
    "3du"
  ],
  "contributors": [
    "clkao",
    "hlb",
    "a-tsioh",
    "pektiong",
    "c9s",
    "miaout17",
    "racklin",
    "poga",
    "caasi"
  ],
  "thumbnail": [
    "https://pbs.twimg.com/media/BQMX_oGCEAIaAEQ.png"
  ],
  "needs": [
    "designer"
  ]
}

=== g0v/ambassador/data/v1/g0v/ly-tel/g0v.json
{
  "author": "billy3321",
  "contributors": [
    "joy hsu",
    "kris chu"
  ],
  "status": "beta",
  "name": "ly-tel",
  "name_zh": "立委聯絡資料",
  "description": "Public participation in tele-form",
  "description_zh": "話筒式的公共參與",
  "homepage": "http://billy3321.github.io/lytel/",
  "document": "",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/ly-tel"
  },
  "licenses": [
    {
      "type": "Apache v2"
    }
  ],
  "keywords": [
    "javascript",
    "jquery",
    "css"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "ly"
  ],
  "thumbnail": "http://billy3321.github.io/lytel/banner_s.jpg",
  "needs": [
    "designer",
    "programmer",
    "writer"
  ]
}

=== g0v/ambassador/data/v1/g0v/datasmith/g0v.json
{
  "author": "poga",
  "contributors": [
    "a",
    "b",
    "c"
  ],
  "status": "alpha",
  "name": "datasmith",
  "name_zh": "datasmith",
  "description": "test",
  "description_zh": "test",
  "homepage": "",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/datasmith"
  },
  "licenses": [
    {
      "type": "MIT"
    }
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "i64885"
  ]
}
