=== g0v/ambassador/bin/schema/v1.json
{
  "id": "https://raw.githubusercontent.com/g0v/ambassador/master/bin/schema/v1.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "author"
  ],
  "properties": {
    "author": {
      "title": "專案作者",
      "description": "Project author",
      "type": "string",
      "minLength": 1
    },
    "status": {
      "title": "專案狀態",
      "description": "Project status",
      "type": "string",
      "enum": [
        "Planning",
        "planning",
        "Pre-alpha",
        "pre-alpha",
        "Alpha",
        "alpha",
        "Beta",
        "beta",
        "Production",
        "production",
        "Released",
        "released",
        "Archived",
        "archived",
        "Stable",
        "stable",
        "Mature",
        "mature",
        "Inactive",
        "inactive",
        "Magic",
        "magic"
      ]
    },
    "name": {
      "title": "專案名稱（英文）",
      "description": "Project name",
      "type": "string",
      "minLength": 1
    },
    "name_zh": {
      "title": "專案名稱（中文）",
      "description": "Chinese project name",
      "type": "string",
      "minLength": 1
    },
    "description": {
      "title": "專案描述（英文）",
      "description": "Project description",
      "type": "string"
    },
    "description_zh": {
      "title": "專案描述（中文）",
      "description": "Chinese project description",
      "type": "string"
    },
    "homepage": {
      "title": "網頁",
      "description": "Homepage url",
      "type": "string",
      "format": "uri"
    },
    "thumbnail": {
      "title": "縮圖",
      "description": "Thumbnail",
      "oneOf": [
        { "type": "string", "format": "uri" },
        { "type": "array", "items": { "type": "string", "format": "uri" } }
      ]
    },
    "document": {
      "title": "文件",
      "description": "Document",
      "type": "string",
      "format": "uri"
    },
    "repository": {
      "title": "Repo 工作資料區",
      "description": "Repository url",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["git", "hg", "svn", "cvs", "svk"]
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": ["type", "url"]
    },
    "licenses": {
      "title": "專案授權",
      "description": "Licenses",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": { "type": "string" }
        },
        "required": ["type"]
      }
    },
    "keywords": {
      "title": "專案關鍵字",
      "description": "Keywords",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "audience": {
      "title": "目標受眾",
      "description": "Target audience",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["contributor", "public", "developer"]
      }
    },
    "products": {
      "title": "產出",
      "description": "Productions",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "partOf": {
      "title": "Part Of",
      "description": "Parent project",
      "type": "string"
    },
    "projects": {
      "title": "Projects",
      "description": "Parent projects",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "contributors": {
      "title": "貢獻者",
      "description": "Contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "needs": {
      "title": "徵求支援",
      "description": "Needs",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["designer", "writer", "programmer", "money", "txt"]
      }
    }
  }
}

=== g0v/ambassador/data/v1/g0v/nuclear-data/g0v.json
{
  "author": "",
  "status": "planning",
  "name": "nuclear-data",
  "description": "Nuclear translate & Watch",
  "description_zh": "將原能會轉譯成容易理解的圖表",
  "homepage": "https://g0v.hackpad.com/-Nuclear-Data-8sYMW30othK",
  "document": "https://g0v.hackpad.com/-Nuclear-Data-8sYMW30othK",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/nuclear-data.git"
  },
  "licenses": [
    {
      "type": "CC:BY-SA"
    }
  ],
  "keywords": [
    "angularjs",
    "python"
  ],
  "audience": [
    "contributor"
  ],
  "products": [
    "website"
  ],
  "projects": [],
  "contributors": [
    "蔡雅瀅",
    "Chang Shu-Huai",
    "Ginger Chen",
    "Jeff Hung",
    "Johnson Liang",
    "nchild",
    "Tom Chen",
    "Tzu-Sheng Wu",
    "Stark"
  ],
  "needs": [
    "designer",
    "writer",
    "programmer"
  ]
}

=== g0v/ambassador/data/v1/g0v/POPonFire/g0v.json
{
  "author": "dz1984",
  "status": "pre-alpha",
  "name": "POPonFire",
  "name_zh": "公有地大行動",
  "description": "To know all POP is our power.",
  "description_zh": "公有土地資料公開，全民監督守護！",
  "homepage": "http://poponfire.herokuapp.com",
  "document": "http://hackfoldr.org/POPonFire",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/POPonFire"
  },
  "licenses": [
    {
      "type": "MIT"
    },
    {
      "type": "CC0"
    }
  ],
  "keywords": [
    "公有地"
  ],
  "audience": [
    "contributor"
  ],
  "products": [
    "website"
  ],
  "projects": [],
  "contributors": [
    "Hoskiss",
    "pm5",
    "ronnywang"
  ],
  "needs": [
    "programmer",
    "designer",
    "writer"
  ]
}

=== g0v/ambassador/data/v1/g0v/moedict-process/g0v.json
{
  "author": "kcwu",
  "status": "stable",
  "name": "moedict-process",
  "description": "parser and format convertor for dictionary data from Ministry of Education",
  "description_zh": "教育部重編國語辭典 資料處理",
  "homepage": "http://3du.tw/",
  "document": "https://github.com/g0v/moedict-process/wiki",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/moedict-process"
  },
  "licenses": [
    {
      "type": "MIT"
    }
  ],
  "keywords": [
    "dictionary",
    "python",
    "parser"
  ],
  "audience": [
    "developer"
  ],
  "products": [
    "data"
  ],
  "projects": [
    "3du"
  ],
  "contributors": [
    "albb0920",
    "au",
    "kcwu",
    "pingooo",
    "viirya"
  ],
  "needs": []
}

=== g0v/ambassador/data/v1/g0v/kuansim/g0v.json
{
  "author": "hychen",
  "contributors": [
    "billy3321",
    "Brecht",
    "ipa",
    "kcliu"
  ],
  "status": "alpha",
  "name": "kuansim",
  "name_zh": "鄉民關心你 - 社會議題追蹤分析網站",
  "description": "society issue tracking system",
  "description_zh": "追蹤各議題狀態以做決策",
  "document": "http://hack.g0v.tw/kuansim",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/kuansim"
  },
  "licenses": [
    {
      "type": "BSD"
    }
  ],
  "keywords": [
    "angularjs",
    "livescript",
    "sass",
    "bootstrap"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "kuansim"
  ],
  "thumbnail": "",
  "needs": [
    "designer",
    "programmer",
    "writer"
  ]
}

=== g0v/ambassador/data/v1/g0v/TWRadiationApp-backend/g0v.json
{
  "author": "",
  "status": "planning",
  "name": "Looknuke Map Web",
  "description": "Looknuke Map Web",
  "description_zh": "輻射地圖網頁版",
  "homepage": "https://g0v.hackpad.com/91ZImrFjGvx",
  "document": "https://g0v.hackpad.com/91ZImrFjGvx",
  "repository": {
    "type": "git",
    "url": "https://github.com/Shihta/Ushahidi_Web.git"
  },
  "licenses": [
    {
      "type": "CC:BY-SA"
    }
  ],
  "keywords": [
    "Nuke",
    "Map"
  ],
  "audience": [
    "contributor"
  ],
  "products": [
    "website"
  ],
  "projects": [],
  "contributors": [
    "Angela 怡",
    "Celine Liang",
    "Charles 呂",
    "Chih Wei",
    "Jimi Chen",
    "Kent Huang",
    "Shihta"
  ],
  "needs": [
    "designer",
    "programmer"
  ]
}

=== g0v/ambassador/data/v1/racklin/moedict-jquery-plugin/g0v.json
{
  "author": "racklin",
  "status": "beta",
  "name": "moedict-jquery-plugin",
  "name_zh": "萌典 jQuery Plugin",
  "description": "Moedict.tw jQuery Plugin",
  "description_zh": "萌典 jQuery Plugin",
  "homepage": "https://github.com/racklin/moedict-jquery-plugin",
  "repository": {
    "type": "git",
    "url": "https://github.com/racklin/moedict-jquery-plugin"
  },
  "keywords": [
    "jquery",
    "dictioanary",
    "livescript",
    "javascript"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "dictionary"
  ],
  "projects": [
    "3du"
  ],
  "contributors": [
    "racklin"
  ],
  "needs": []
}

=== g0v/ambassador/data/v1/g0v/kuansim-frontend/g0v.json
{
  "author": "hychen",
  "contributors": [
    "Brecht",
    "kcliu"
  ],
  "status": "alpha",
  "name": "kuansim-frontend",
  "name_zh": "鄉民關心你 - 社會議題追蹤分析網站 前端",
  "description": "society issue tracking system",
  "description_zh": "追蹤各議題狀態以做決策",
  "document": "http://hack.g0v.tw/kuansim",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v/kuansim-frontend"
  },
  "licenses": [
    {
      "type": "BSD"
    }
  ],
  "keywords": [
    "angularjs",
    "livescript",
    "sass",
    "bootstrap"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "kuansim"
  ],
  "thumbnail": "",
  "needs": [
    "designer",
    "programmer",
    "writer"
  ]
}

=== g0v/ambassador/data/v1/g0v/congress-vote-analytics-beta/g0v.json
{
  "author": "bater",
  "contributors": [
    "bater",
    "fntsrlike"
  ],
  "status": "beta",
  "homepage": "http://va.twbbs.org/",
  "name": "VotesAnalysis",
  "name_zh": "選 票 成 份 分 析",
  "description": "Let us know which one legislator (Or politicians) and their position closest to the voters.",
  "description_zh": "了解哪一個立委(政治人物)與選民自己的立場最接近。",
  "document": "https://g0v.hackpad.com/YpOT9vjLthf",
  "repository": {
    "type": "git",
    "url": "https://github.com/g0v-tw-congress-vote-analytics/congress-vote-analytics-beta"
  },
  "licenses": [
    {
      "type": "MIT License"
    }
  ],
  "keywords": [
    "bater",
    "立法院"
  ],
  "audience": [
    "public"
  ],
  "products": [
    "website"
  ],
  "projects": [
    "立法院小組"
  ],
  "thumbnail": "",
  "needs": [
    "designer",
    "programmer",
    "writer"
  ]
}
